### ISSUE TITLE
Version 3.0.2 break compilation on pypy

### ISSUE THREAD

**Issue by fruch** [python-lz4/python-lz4#194]
```
lz4/_version.c:39:65: error: redefinition of parameter â€˜Py_UNUSEDâ€™
   library_version_number (PyObject * Py_UNUSED (self), PyObject * Py_UNUSED (args))
                                                                   ^
```
Full log:
https://api.travis-ci.org/v3/job/661421436/log.txt

On version 2.2.1 it was compiling o.k.

**Comment by jonathanunderwood** [comment]
It looks like PyPy doesn't define `Py_UNUSED`. 

Prior to version 3  we used the py3c package to provide missing macro definitions for Pythons earlier than 3.5.  With version 3.0.0 we dropped support for Python < 3.5, and remove the py3c library.

The best fix here would actually be to add Py_UNUSED to PyPy.

**Comment by vmihailenco** [comment]
I have the same problem too. Can't we just revert https://github.com/python-lz4/python-lz4/commit/4b26dca06d9d89ff7cac496c85397158d60e2cee? It seems harmless and more practical than waiting for PyPy to be updated...

**Comment by jonathanunderwood** [comment]
Has anyone raised an issue against pypy?

**Comment by jonathanunderwood** [comment]
https://foss.heptapod.net/pypy/pypy/issues/3245

**Comment by jonathanunderwood** [comment]
Should be fixed in 3.1.0.

**Comment by mycroft** [comment]
Hello, I'm still having the same issue, using `pypy3.6-7.1.1-beta-linux_x86_64-portable.tar.bz2` & `lz4-3.1.0.tar.gz`. Unfortunately, the macro seems to be used in several place in `lz4` (`lz4/frame/_frame.c, lz4/stream/_stream.c and lz4/_version.c`) and the recent revert seems to fix the problem only into `lz4/block/_block.c`, so... Would you accept a PR regarding this ?

Thanks you.

**Comment by jonathanunderwood** [comment]
https://foss.heptapod.net/pypy/pypy/issues/3245

```
Can you clarify which pypy version you're talking about? Py_UNUSED is defined in the cpyext headers for pypy3.
```

Looks like the right fix is to conditionally include the cpyext headers if building on pypy3. I would happily accept a patch which implemented that.

**Comment by mycroft** [comment]
Yeah, well, then I think I found our issue. Obviously the problem is not in `python-lz4`, but in [pypy3.x portable packages currently hosted on bitbucket](https://bitbucket.org/squeaky/portable-pypy/downloads/). The problem is that in pacakges we are using (I'm using `pypy3.6-7.1.1-beta-linux_x86_64-portable` and you were using on Travis `pypy3.5.tar.bz2` which is bundling the `pypy3.5-5.10.1` portable), there is a `pymacro.h` file without the `Py_UNUSED` macro, when official pypy releases have the macros... I realized that when I successfully compiled python-lz4 on the official `pypy3.6-7.3.1` docker image. Those portable packages are the culprit here.

The good news is that latest portable package, [now hosted on github](https://github.com/squeaky-pl/portable-pypy/releases), have the macros and now are working better. Version is `pypy3.6-7.2.0-linux_x86_64-portable`. I guess I will start using that updated version.
